CREATE OR REPLACE TRIGGER "CLCL_BIU_TR" 
 BEFORE INSERT OR UPDATE OF CLAS_OID_CLAS
 ON MAE_CLIEN_CLASI
 FOR EACH ROW
BEGIN

SELECT TCCL_OID_TIPO_CLAS
INTO :NEW.TCCL_OID_TIPO_CLASI
FROM MAE_CLASI
WHERE OID_CLAS = :NEW.CLAS_OID_CLAS;
:new.fec_ulti_actu := sysdate;
END;
/

