CREATE OR REPLACE VIEW V_USU_LARGO AS
SELECT us_ex.IDUSER AS IDUSUARIO, pr_ex.NAME AS NOMBREUSUARIO, 
	      NVL((SELECT p.STRINGVALUE FROM PROPERTYVALUES p, PRINCIPALS pr_in, USERS us WHERE pr_in.IDPRINCIPAL=pr_ex.IDPRINCIPAL AND us.IDUSER=p.IDPRINCIPAL AND pr_in.IDPRINCIPAL=p.IDPRINCIPAL AND p.IDPROPERTY=2),'') AS APELLIDOPATERNO, 
	      NVL((SELECT p.STRINGVALUE FROM PROPERTYVALUES p, PRINCIPALS pr_in, USERS us WHERE pr_in.IDPRINCIPAL=pr_ex.IDPRINCIPAL AND us.IDUSER=p.IDPRINCIPAL AND pr_in.IDPRINCIPAL=p.IDPRINCIPAL AND p.IDPROPERTY=3),'') AS APELLIDOMATERNO, 
	      NVL((SELECT p.STRINGVALUE FROM PROPERTYVALUES p, PRINCIPALS pr_in, USERS us WHERE pr_in.IDPRINCIPAL=pr_ex.IDPRINCIPAL AND us.IDUSER=p.IDPRINCIPAL AND pr_in.IDPRINCIPAL=p.IDPRINCIPAL AND p.IDPROPERTY=5),'') AS NOMBRE1, 
	      NVL((SELECT p.STRINGVALUE FROM PROPERTYVALUES p, PRINCIPALS pr_in, USERS us WHERE pr_in.IDPRINCIPAL=pr_ex.IDPRINCIPAL AND us.IDUSER=p.IDPRINCIPAL AND pr_in.IDPRINCIPAL=p.IDPRINCIPAL AND p.IDPROPERTY=6),'') AS NOMBRE2 
FROM PRINCIPALS pr_ex, USERS us_ex WHERE us_ex.IDUSER=pr_ex.IDPRINCIPAL;

