CREATE OR REPLACE TRIGGER "ROUA_TR_B_I" BEFORE INSERT ON REC_REPOR_OPERA_UNIDA_ADMIN
FOR EACH ROW
BEGIN
  SELECT    SEQ_REPOR_OPERA_UNIDA_ADMIN.NEXTVAL
    INTO    :NEW.NUM_ITEM
  FROM      DUAL;
END;
/

