CREATE OR REPLACE PROCEDURE "OBT_INDIC_REVISION_APP" (
OID_CONSOLIDADO NUMBER,
V_AUX NUMBER
)
IS
PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  UPDATE PED_SOLIC_CABEC SET INRE_OID_INDI_REVI = V_AUX WHERE OID_SOLI_CABE = OID_CONSOLIDADO;
  COMMIT;
END;
/

