package biz.belcorp.ssicc.web.seguridad.form;

import java.util.ArrayList;
import java.util.List;

import biz.belcorp.ssicc.web.framework.base.form.BaseEditForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 */

public class MenuForm extends BaseEditForm {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1552652671971689208L;

	/**
     * Holds value of property codigo.
     */
    protected String codigo;

    /**
     * Holds value of property descripcion.
     */
    protected String descripcion;

    /**
     * Holds value of property informacionAyuda.
     */
    protected String informacionAyuda;

    /**
     * Holds value of property codigoPadre.
     */
    protected String codigoPadre;

    /**
     * Holds value of property codigoProceso.
     */
    protected String codigoProceso;

    /**
     * Holds value of property descripcionPadre.
     */
    protected String descripcionPadre;

    /**
     * Holds value of property accion.
     */
    protected String accion;

    /**
     * Holds value of property pagina.
     */
    protected String pagina;

    /**
     * Holds value of property nivel.
     */
    protected String nivel;

    /**
     * Holds value of property posicion.
     */
    protected String posicion;

    /**
     * Holds value of property estado.
     */
    protected String estado;

    /**
     * Holds value of property parametrosForm.
     */
    protected List<ParametroMenuForm> parametrosMenuForm;

	/** Default empty constructor. */
    public MenuForm() {
    	parametrosMenuForm = new ArrayList();
    }
    
    protected String codigoOpciones;
    
    protected String codigoMenu;
    
	private String[] botonesAsignados;

	private String[] botonesNoAsignados;

	protected String[] selectedItems = {};

	protected String selectedItem = null;
	
	protected String nombreParametro;
	
	protected String valorParametro;

	/**
     * Getter for property codigo.
     * 
     * @return Value of property codigo.
     */
    public String getCodigo() {
        return this.codigo;
    }

    /**
     * Setter for property codigo.
     * 
     * @param codigo
     *            New value of property codigo.
     */
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    /**
     * @return Returns the codigoProceso.
     */
    public String getCodigoProceso() {
        return codigoProceso;
    }

    /**
     * @param codigoProceso
     *            The codigoProceso to set.
     */
    public void setCodigoProceso(String codigoProceso) {
        this.codigoProceso = codigoProceso;
    }

    /**
     * Getter for property descripcion.
     * 
     * @return Value of property descripcion.
     */
    public String getDescripcion() {
        return this.descripcion;
    }

    /**
     * Setter for property descripcion.
     * 
     * @param descripcion
     *            New value of property descripcion.
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * @return Returns the informacionAyuda.
     */
    public String getInformacionAyuda() {
        return informacionAyuda;
    }

    /**
     * @param informacionAyuda The informacionAyuda to set.
     */
    public void setInformacionAyuda(String informacionAyuda) {
        this.informacionAyuda = informacionAyuda;
    }

    /**
     * Getter for property codigoPadre.
     * 
     * @return Value of property codigoPadre.
     */
    public String getCodigoPadre() {
        return this.codigoPadre;
    }

    /**
     * @return Returns the descripcionPadre.
     */
    public String getDescripcionPadre() {
        return descripcionPadre;
    }

    /**
     * @param descripcionPadre
     *            The descripcionPadre to set.
     */
    public void setDescripcionPadre(String descripcionPadre) {
        this.descripcionPadre = descripcionPadre;
    }

    /**
     * Setter for property codigoPadre.
     * 
     * @param codigoPadre
     *            New value of property codigoPadre.
     */
    public void setCodigoPadre(String codigoPadre) {
        this.codigoPadre = codigoPadre;
    }

    /**
     * Getter for property accion.
     * 
     * @return Value of property accion.
     */
    public String getAccion() {
        return this.accion;
    }

    /**
     * Setter for property accion.
     * 
     * @param accion
     *            New value of property accion.
     */
    public void setAccion(String accion) {
        this.accion = accion;
    }

    /**
     * @return Returns the pagina.
     */
    public String getPagina() {
        return pagina;
    }

    /**
     * @param pagina
     *            The pagina to set.
     */
    public void setPagina(String pagina) {
        this.pagina = pagina;
    }

    /**
     * Getter for property nivel.
     * 
     * @return Value of property nivel.
     */
    public String getNivel() {
        return this.nivel;
    }

    /**
     * Setter for property nivel.
     * 
     * @param nivel
     *            New value of property nivel.
     */
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }

    /**
     * Getter for property posicion.
     * 
     * @return Value of property posicion.
     */
    public String getPosicion() {
        return this.posicion;
    }

    /**
     * Setter for property posicion.
     * 
     * @param posicion
     *            New value of property posicion.
     */
    public void setPosicion(String posicion) {
        this.posicion = posicion;
    }

    /**
     * @return Returns the estado.
     */
    public String getEstado() {
        return estado;
    }

    /**
     * @param estado
     *            The estado to set.
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

	public String getCodigoMenu() {
		return codigoMenu;
	}

	public void setCodigoMenu(String codigoMenu) {
		this.codigoMenu = codigoMenu;
	}

	public String getCodigoOpciones() {
		return codigoOpciones;
	}

	public void setCodigoOpciones(String codigoOpciones) {
		this.codigoOpciones = codigoOpciones;
	}

	public String[] getBotonesAsignados() {
		return botonesAsignados;
	}

	public void setBotonesAsignados(String[] botonesAsignados) {
		this.botonesAsignados = botonesAsignados;
	}

	public String[] getBotonesNoAsignados() {
		return botonesNoAsignados;
	}

	public void setBotonesNoAsignados(String[] botonesNoAsignados) {
		this.botonesNoAsignados = botonesNoAsignados;
	}

	public String getSelectedItem() {
		return selectedItem;
	}

	public void setSelectedItem(String selectedItem) {
		this.selectedItem = selectedItem;
	}

	public String[] getSelectedItems() {
		return selectedItems;
	}

	public void setSelectedItems(String[] selectedItems) {
		this.selectedItems = selectedItems;
	}

    /**
	 * @return the parametrosForm
	 */
	public List<ParametroMenuForm> getParametrosMenuForm() {
		return parametrosMenuForm;
	}

	/**
	 * @param parametrosForm the parametrosForm to set
	 */
	public void setParametrosMenuForm(List<ParametroMenuForm> parametrosMenuForm) {
		this.parametrosMenuForm = parametrosMenuForm;
	}

    /**
	 * @return the nombreParametro
	 */
	public String getNombreParametro() {
		return nombreParametro;
	}

	/**
	 * @param nombreParametro the nombreParametro to set
	 */
	public void setNombreParametro(String nombreParametro) {
		this.nombreParametro = nombreParametro;
	}

	/**
	 * @return the valorParametro
	 */
	public String getValorParametro() {
		return valorParametro;
	}

	/**
	 * @param valorParametro the valorParametro to set
	 */
	public void setValorParametro(String valorParametro) {
		this.valorParametro = valorParametro;
	}
	
	/* NUEVO ACTUALIZACION FRAMEWORK JSF */
		
	private String paginaXml;

	/**
	 * @return the paginaXml
	 */
	public String getPaginaXml() {
		return paginaXml;
	}

	/**
	 * @param paginaXml the paginaXml to set
	 */
	public void setPaginaXml(String paginaXml) {
		this.paginaXml = paginaXml;
	}
	
	
}
