package biz.belcorp.ssicc.web.seguridad.form;

import biz.belcorp.ssicc.web.framework.base.form.BaseEditForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 */

public class RolForm extends BaseEditForm{

    /**
	 * 
	 */
	private static final long serialVersionUID = -5826709724164595606L;

	/**
     * Holds value of property codigoPais.
     */
    protected String codigoPais;

    /**
     * Holds value of property codigo.
     */
    protected String codigo;

    /**
     * Holds value of property descripcion.
     */
    protected String descripcion;

    /**
     * Holds value of property estado.
     */
    protected String estado;

    /**
     * Holds value of property descripcionPais.
     */
    protected String descripcionPais;

    /** Default empty constructor. */
    public RolForm() {
    }

    /**
     * @return Returns the codigoPais.
     */
    public String getCodigoPais() {
        return codigoPais;
    }

    /**
     * @param codigoPais
     *            The codigoPais to set.
     * @struts.validator type="required"
     */
    public void setCodigoPais(String codigoPais) {
        this.codigoPais = codigoPais;
    }

    /**
     * Getter for property codigo.
     * 
     * @return Value of property codigo.
     */
    public String getCodigo() {
        return this.codigo;
    }

    /**
     * Setter for property codigo.
     * 
     * @param codigo
     *            New value of property codigo.
     */
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    /**
     * Getter for property descripcion.
     * 
     * @return Value of property descripcion.
     */
    public String getDescripcion() {
        return this.descripcion;
    }

    /**
     * Setter for property descripcion.
     * 
     * @param descripcion
     *            New value of property descripcion.
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * Getter for property estado.
     * 
     * @return Value of property estado.
     */
    public String getEstado() {
        return this.estado;
    }

    /**
     * Setter for property estado.
     * 
     * @param estado
     *            New value of property estado.
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * Getter for property descripcionPais.
     * 
     * @return Value of property descripcionPais.
     */
    public String getDescripcionPais() {
        return descripcionPais;
    }

    /**
     * Setter for property descripcionPais.
     * 
     * @param descripcionPais
     *            New value of property descripcionPais.
     */
    public void setDescripcionPais(String descripcionPais) {
        this.descripcionPais = descripcionPais;
    }

    protected boolean seleccionarTodo;

	/**
	 * @return the seleccionarTodo
	 */
	public boolean isSeleccionarTodo() {
		return seleccionarTodo;
	}

	/**
	 * @param seleccionarTodo the seleccionarTodo to set
	 */
	public void setSeleccionarTodo(boolean seleccionarTodo) {
		this.seleccionarTodo = seleccionarTodo;
	}
   
}
