CREATE OR REPLACE TRIGGER BAS_TRG_AI_REPOR_EJECU_ACTUA
  AFTER INSERT ON BAS_REPOR_EJECU_ACTUA
  FOR EACH ROW
DECLARE

BEGIN
      /* Insercion la tabla BAS_PROCE_BATCH_HISTO */
      INSERT INTO BAS_REPOR_EJECU_HISTO
      (
     NUM_SEQU,
     PAIS_COD_PAIS,
     COD_MENU,
     COD_REPO,
     NOM_ARCH_REPO,
     VAL_IP_MAQU,
     COD_USUA,
     COD_PERI,
     FEC_INIC_REPO,
     FEC_FINA_REPO,
     VAL_FORM_REPO,
     NUM_DURA_SEGU,
     IND_MULTI_REPO,
     VAL_REPO_GENE,
     IND_ENVIO_EMAIL,
	 IND_ERRO
     )
      VALUES
      (
     :NEW.NUM_SEQU,
     :NEW.PAIS_COD_PAIS,
     :NEW.COD_MENU,
     :NEW.COD_REPO,
     :NEW.NOM_ARCH_REPO,
     :NEW.VAL_IP_MAQU,
     :NEW.COD_USUA,
     :NEW.COD_PERI,
     :NEW.FEC_INIC_REPO,
     :NEW.FEC_FINA_REPO,
     :NEW.VAL_FORM_REPO,
     :NEW.NUM_DURA_SEGU,
     :NEW.IND_MULTI_REPO,
     :NEW.VAL_REPO_GENE,
     :NEW.IND_ENVIO_EMAIL,
	 :NEW.IND_ERRO
    );

END BAS_TRG_AI_REPOR_EJECU_ACTUA;
/
