CREATE OR REPLACE TRIGGER BAS_TRG_AU_AUDI_PROCE_USUA
  AFTER UPDATE ON BAS_AUDI_PROCE_USUA_ACTUA
  FOR EACH ROW
DECLARE

BEGIN

     /* Actualizaci?n la tabla BAS_PROCE_BATCH_HISTO */

    UPDATE BAS_AUDI_PROCE_USUA_HISTO
    SET
       PAIS_COD_PAIS  = :NEW.PAIS_COD_PAIS,
       COD_MENU       = :NEW.COD_MENU,
       COD_ACCI       = :NEW.COD_ACCI,
       VAL_IP_MAQU    = :NEW.VAL_IP_MAQU,
       COD_USUA       = :NEW.COD_USUA,
       COD_PERI       = :NEW.COD_PERI,
       FEC_INIC_PROC  = :NEW.FEC_INIC_PROC,
       FEC_FINA_PROC  = :NEW.FEC_FINA_PROC,
       NUM_DURA_SEGU  = :NEW.NUM_DURA_SEGU,
       IND_ESTA_PROC  = :NEW.IND_ESTA_PROC
    WHERE
       NUM_SEQU     = :NEW.NUM_SEQU ;

END BAS_TRG_AU_AUDI_PROCE_USUA;
/
